cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    None:
      email: ''
      failed_login_attempts: 0
      logged_in: false
      name: ''
      password: ''
preauthorized:
  emails:
