# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://kprwswhsdkeacjpwpsjj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwcndzd2hzZGtlYWNqcHdwc2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjAxNjYxMjgsImV4cCI6MjAzNTc0MjEyOH0.gNfUqZzn9tY-awZhH6u3Vo1RqYtxdy9yupvm7RJcdMw"
